target-version = "py312"
line-length = 120

[lint]
select = ["E", "W", "F", "B", "UP", "D", "SIM", "I", "ANN", "S", "C4", "NPY", "RUF"]
ignore = [
    "E501",
    "W293",
    "B905",
    "UP015",
    "D103",
    "D401",
    "D403",
    "C408"
]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"
avoid-escape = false

[format]
quote-style = "single"
line-ending = "cr-lf"
skip-magic-trailing-comma = true
